site_name: Gitlint
site_description: Linting for your git commit messages
site_url: http://jorisroovers.github.io/gitlint/
repo_url: https://github.com/jorisroovers/gitlint
pages:
    - Home: index.md
    - Configuration: configuration.md
    - Rules: rules.md
    - Contrib Rules: contrib_rules.md
    - User Defined Rules: user_defined_rules.md
    - Contributing: contributing.md

markdown_extensions: [admonition]
theme: readthedocs
strict: true
